server:
  port: 8150
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:postgresql://185.204.217.194:5432/ml-db
    username: martal
    password: ml-12345

  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true

      database-platform: org.hibernate.dialect.PostSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          temp:
            use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    drop-first: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
